defaults:
  - override hydra/sweeper: hypersweeper

hydra:
  sweeper:
    backend: smac
    smac:
      budget: 5             # Ges. Evaluierungen
      maximize: true         # Return maximieren

    params:
      env.name:
        - CartPole-v1
        - LunarLander-v3
      agent.baseline_type:
        - none
        - avg,
        - value,
        - gae
      seed:
        range(0, 5)
